language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r test_requirements.txt
env:
  matrix:
  - TEST_ENV=travis
  global:
    secure: iDC1z+t4xhD5wk3runujsM/m9pAYpXMZb+/ufAOL4GxtXCu2Vv2tDV9SCGiQXTd8ogJYeF87wnmDNgfouBar2mPRZ8UsSKpLmjf0hniUVfBHZp9osu0y89frKNEfQ4Z3lcaG3nyRV+A9zS7hNxNh7xTGx1FE9WvGtV4BiPnG+DLAWNIAlbINYEc2ogspEG0pPOT0IpgemslzV5gRxrT0mPgCB5w2rZZnBu+Mqc7+9Q6n7kAl+naqFLZ3obpkg7KEjSbMwFso6NxQZfzSiRKG6MpOWVbfSArOMNT/rXlp+HReCbMPA8xCP7j5WrZHmzyItz1dlhrHtdpyw+QbwMCNs5ar37F3C9YdssCpuofojDr4VjcNksJtC8EgmOuohzQ8XG52PnWJY8/AW48NdfYMM+hoqBDdOwGSrJj2wocW9NLP9E00lI2fC0UmW/1Q+tJqcd5zIlNbXM4mLt5+itx+AGmxHm3k1kB6/p42FwoQNtoWXzkx0pHh9VfJ9dovGjjtZtjiN0aSTwRQocH7zgVrymytoaYRZXqvAyyPWBwi1BkUOhpEcj5WV6cIBZri0Etar17pYqGGPlU1BzJ7YkfqK+MGu41dxRAmDJO0hKk970slt16E9mRB8BSJPKwY3Ji+odn/wS6DaqOi/Uth2Zzw0RXezS3RkKDa3KuK4DCODhs=
script:
- flake8 . && travis_wait 50 py.test
before_install:
- openssl aes-256-cbc -K $encrypted_a7c8f759f73f_key -iv $encrypted_a7c8f759f73f_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mv .globus-native-apps.cfg ~/.globus-native-apps.cfg
- mv .client_credentials.json ~/.client_credentials.json
after_success:
- coveralls
notifications:
  email:
    recipients:
    - blaiszik@uchicago.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: PeTw4hgPe/UvQXjmYD7tT+4J1tOZKOHw5sLYegSZtnekKeLpjLZib0eZrAkzE5LFbRoRgXZ9z4Yn+hN3az4Z1GodXYcRrYrvRwe75oZMgxe5TvXpmE1lqv8nCvbDo2LJbkVTdn0fKRRfEl1W62RtYcyh+QwunUudHA9U2zOZLqSt4BeYMTOK4T5XyhZ5T1DYSBO8Dj28OFuemjwGkBMgZ5Z/+GqIJ1wZw2sKHKN+vkKj8NChPEzok+GX0R1CXgqvMMHPNJUx/69hZMuqxZciQICqhAstUw//ssTI6bzGHivbhObE5nlDqmBIPDD8tEG6p/XOOFtHx2a/R6KV+5wjzIs6sLiEz2QAG/qKm20jSHi8j585RqjgpBGC1g0FQ8k75E0oF8ls5unHFnDHPRWnPI0ifZ2qgYIUWdHC6dV4QF06Z1OYRHfOiyiLvuWIlKufKRM6aC84LEXxBS7Lq4MUZ+wKjGVf5EmSeJzYC+NXnBcnkFOx3KnImNDP9JuBwsgrFYRZhpvlwKdmCn1sw+iAuhco+nTKrzq5fK4vglE4zAMr81YgnLrVY3xJrz0G4wbQYvtxcFx84GaV6UiL1hfbuu4aBw3o6kuq5gxEaYg18MvsIZyIbQOpNuqRtQsHknRJSoLPvIEv8Rq6zA2twHI1MJXunjzsc0WaCm2Npt1ZpGk=
deploy:
  provider: pypi
  user: __token__
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: s+rnlMOHQuV195S7ZWtMpoUsfFO/rPqJVLcNvC8/RO2hfJzipc8xYmfeXGEYqWZQ+eSpbEO0WkpZqRgk8O7FUDJxo9Rt5pfkjNEZoZWPYQBzFIL37kgZiAhgjSjPkF3uqbpaayHeCtLvbjYIcdUXzNd1Mi9hc/xA8X3loMTYaCIF3vCO7lcwTzEHQV4VRjszxo3lz4UNqvXhZQhytfM81wPZXKT8cOMiq7T0wGaH8Ap9x2fFZfQ1ipb8OoOXPwDPznU0s6yE6GVvMphzz/JO3q8myzdl4A6e37JUEsbrD5+hr7D5rzCVIyANcHe+cZ7w9vqV6ijAFDS9nILscZzgWsS1BKrcHLlRxQyhyro9VX43WhQ+RjtCTKcaSzq7MJIeXySDjjXZSJNbEyIL++BqhxyYDm5F6JSDeTgpUZjgwOP9kFEAh2x5sxye0Hd4ocvgzqpZ0+Va2/qgmW8+JBUKnYpFuZD69Wt6tr0KYw7y2UI/fLEEXLCWlATRxoIKqR0fdITbL6KekzjX0SvBUJPuSAjEwEiravTz5j3laOIBzqv/wiGXyApY/Mw84/PiIUeXDzWrYNmBKubqlQXssRJ9xqrB06jrC203MNP3PODl4uIceOjqGVtFlEIm4sWBVutxSnMojqRC3IV/sJKENg3LwNOkrusr7wdxHD/BfHS7evk=
